env:
  browser: true
  es2021: true
  es6: true
  node: true
  jest: true
  jquery: true
extends:
  - plugin:react/recommended
  - standard
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
settings:
  react:
    version: 'detect'
rules: {
  semi: ['error', 'always'],
  comma-dangle: ['error', 'always-multiline'],
}
