version: "3"
services:
  db:
    image: postgres
    volumes: 
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  web:
    build:
      context: .
      dockerfile: Dockerfile 
    image: skhan1211/mct-fx-signals:0.1
    volumes:
      - .:/my_app
    ports: 
      - "3000:3000"
    depends_on: 
      - db
    environment: 
      DATABASE_URL: postgres://postgres@db