branch-defaults:
  master:
    environment: MCTFXSignals-web
environment-defaults:
  MCTFXSignals-web:
    branch: null
    repository: null
global:
  application_name: MCT FX Signals
  default_ec2_keyname: null
  default_platform: Puma with Ruby 2.5 running on 64bit Amazon Linux
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
